config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'drinks#index'
  get 'about' => 'about#index'

  get 'find_drink', to: 'drinks#find_drink'
  post 'match_drinks', to: 'drinks#match_drinks', as: 'match_drinks'

  resources :drinks
  resources :categories
  resources :ingredients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :drinks
  default_scope -> { order(name: :asc) }
  validates :name, presence: true,
                   length: { minimum: 3 }
end

app/models/drink.rb
# frozen_string_literal: true

class Drink < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_and_belongs_to_many :ingredients
  accepts_nested_attributes_for :ingredients
  has_attached_file :image, styles: { large: 'x250' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :name, presence: true
end

app/models/drinks_ingredient.rb
# frozen_string_literal: true

class DrinksIngredient < ApplicationRecord
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_and_belongs_to_many :drinks
  default_scope -> { order(name: :asc) }

  validates :name, presence: true,
                   length: { minimum: 3 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :drinks
  validates :password, presence: true,
                       length: { minimum: 5 }
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index
    @page_title = 'About Me'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attributes = [:email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit(:sing_up, keys: added_attributes)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Primary Alcohol'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category Created'

      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    @category.update(category_params)

    flash[:notice] = 'Category Updated'

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])

    @category.destroy

    flash[:notice] = 'Category Removed'

    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @drinks = @category.drinks
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/drinks_controller.rb
# frozen_string_literal: true

class DrinksController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def new
    @page_title = 'Add Drink'
    @drink = current_user.drinks.build
    @ingredients = Ingredient.all

    # @category = current_user.categories.build
    # @ingredient = current_user.ingredients.build
  end

  def create
    @drink = current_user.drinks.build(drink_params)
    if @drink.save
      @drink.ingredients << Ingredient.where(id: params[:id])

      flash[:notice] = 'Drink Created'

      redirect_to drinks_path
    else
      render 'new'
    end
  end

  def update
    @drink = current_user.drinks.find(params[:id])

    @drink.update(drink_params)

    flash[:notice] = 'Drink Updated'

    redirect_to drinks_path
  end

  def edit
    @drink = current_user.drinks.find(params[:id])
  end

  def destroy
    @drink = current_user.drinks.find(params[:id])

    @drink.destroy

    flash[:notice] = 'Drink Removed'

    redirect_to drinks_path
  end

  def index
    @drinks = Drink.all
    @categories = Category.all
  end

  def show
    @drink = Drink.find(params[:id])
    @categories = Category.all
    @ingredients = Ingredient.all
  end

  def find_drink
    @page_title = 'Find Drink!'
    @drink = Drink.new
    @ingredients = Ingredient.all
  end

  def match_drinks
    @page_title = 'Matched Drinks'
    params_ingredient_ids = drink_params['ingredient_ids']
    @drinks = Drink.select do |drink|
      (drink.ingredient_ids & params_ingredient_ids.map(&:to_i)).any?
    end
    @sorted_drinks = @drinks.sort { |drink| (drink.ingredient_ids & params_ingredient_ids.map(&:to_i)).length }
    @categories = Category.all
  end

  private

  def drink_params
    params.require(:drink).permit!
  end

  def ingredient_params
    params.require(:ingredient).permit(:id, :name)
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  def new
    @page_title = 'Add New Ingredient'
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:notice] = 'Ingredient Created'

      redirect_to ingredients_path
    else
      render 'new'
    end
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    @ingredient.update(ingredient_params)

    flash[:notice] = 'Ingredient Updated'

    redirect_to ingredient_path
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])

    @ingredient.destroy

    flash[:notice] = 'Ingredient Removed'

    redirect_to ingredients_path
  end

  def index
    @ingredients = Ingredient.all
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:id, :name)
  end
end

app/helpers/about_helper.rb
# frozen_string_literal: true

module AboutHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/drinks_helper.rb
# frozen_string_literal: true

module DrinksHelper
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Information about me</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2>Edit Primary Alcohol</h2>

<%= form_for @category do |f| %>
  <!-- Check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", categories_path, class:'btn btn-default' %>
  
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
  <tr>
    <th>Primary Alcohol Name</th>
    <th>Actions</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Edit', edit_category_path(category.id) %> | <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h2> Add New Primary Alcohol</h2>

<%= form_for @category do |f| %>
  <!-- Check for errors -->
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", categories_path, class:'btn btn-default' %>
  
<% end %>

app/views/categories/show.html.erb
<h2><i><%= @category.name %></i></h2>
<div id="drinks-index">
  <% @drinks.each_slice(4) do |drink| %>
    <div class="row">
      <% drink.each do |drink| %>
        <div class="col-md-3 col-sm-3">
        <h3><%= drink.name %></h3>
        <%= image_tag drink.image.url %>
        <%= link_to 'Read More', drink_path(drink), class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/drinks/create.html.erb
<h1>Drinks#create</h1>
<p>Find me in app/views/drinks/create.html.erb</p>

app/views/drinks/destroy.html.erb
<h1>Drinks#destroy</h1>
<p>Find me in app/views/drinks/destroy.html.erb</p>

app/views/drinks/edit.html.erb
<h2>Edit Drink</h2>

<%= form_for @drink, html: {multipart: true} do |f| %>
  <!-- Check for errors -->
  <% if @drink.errors.any? %>
    <% @drink.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :category %><br />
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br /><br />
  </div>

  <div class="form-group", id='add_ingredients'>
    <%= f.label :ingredient %><br />
    <% Ingredient.all.each do |ingredient| %>
      <%= check_box_tag "drink[ingredient_ids][]", ingredient.id, class:'form-control' %><br />
      <%= ingredient.name %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :preparation %><br />
    <%= f.text_area :preparation, class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :image %><br />
    <%= f.file_field :image %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", drinks_path, class:'btn btn-default' %>

<% end %>

app/views/drinks/find_drink.html.erb
<h2><i class="fas fa-cocktail"></i>
Select the ingredients that you have</h2>

<%= form_for(@drink, url: match_drinks_path) do |f| %>
  <!-- Check for errors -->
  <% if @drink.errors.any? %>
    <% @drink.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group", id='add_ingredients'>
    <% f.label :ingredient %><br />
    <% Ingredient.all.each do |ingredient| %>
      <%= check_box_tag "drink[ingredient_ids][]", ingredient.id %>
      <%= ingredient.name %>
    <% end %>
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", drinks_path, class:'btn btn-default' %>

<% end %>

app/views/drinks/index.html.erb
<div id="drinks-index">
  <% @drinks.each_slice(4) do |drink| %>
    <div class="row">
      <% drink.each do |drink| %>
        <div class="col-md-3 col-sm-3">
        <h3><%= drink.name %></h3>
        <%= image_tag drink.image.url %>
        <%= link_to 'Read More', drink_path(drink), class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/drinks/match_drinks.html.erb
<div id="drinks-index">
  <% @sorted_drinks.each_slice(4) do |drink| %>
    <div class="row">
      <% drink.each do |drink| %>
        <div class="col-md-3 col-sm-3">
        <h3><%= drink.name %></h3>
        <%= image_tag drink.image.url %>
        <%= link_to 'Read More', drink_path(drink), class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/drinks/new.html.erb
<h2>Add New Drink</h2>

<%= form_for @drink, html: {multipart: true} do |f| %>
  <!-- Check for errors -->
  <% if @drink.errors.any? %>
    <% @drink.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :category %><br />
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %><br /><br />
  </div>

  <div class="form-group", id='add_ingredients'>
    <%= f.label :ingredient %><br />
    <% Ingredient.all.each do |ingredient| %>
      <%= check_box_tag "drink[ingredient_ids][]", ingredient.id %>
      <%= ingredient.name %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :preparation %><br />
    <%= f.text_area :preparation, class:'form-control' %><br />
  </div>

  <div class="form-group">
    <%= f.label :image %><br />
    <%= f.file_field :image %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", drinks_path, class:'btn btn-default' %>

<% end %>

app/views/drinks/show.html.erb
<div id="drinks-show">
  <h2><%= @drink.name %></h2>
  <div class="drinks-show-left">
    <%= image_tag @drink.image.url %>
  </div>
  <div class="drinks-show-right">
    <h3><strong>Primary alcohol: </strong><%= @drink.category.name %></h3>
    <ul>
      <li><strong>Ingredients:</strong>
        <p><% @drink.ingredients.each do |i| %>
          <%= i.name %>
        <% end %></p>
      </li>
      <li><strong>Preparation:</strong>
        <p><%= @drink.preparation %></p>
      </li>
  </div>
  <div class="clearfix"></div>
  <% if user_signed_in? %>
  <%= link_to 'Edit', edit_drink_path(@drink.id) %> | <%= link_to 'Delete', drink_path(@drink), method: :delete, data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>

app/views/drinks/update.html.erb
<h1>Drinks#update</h1>
<p>Find me in app/views/drinks/update.html.erb</p>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/destroy.html.erb
<h1>Ingredients#destroy</h1>
<p>Find me in app/views/ingredients/destroy.html.erb</p>

app/views/ingredients/edit.html.erb
<h2> Edit Ingredient</h2>

<%= form_for @ingredient do |f| %>
  <!-- Check for errors -->
  <% if @ingredient.errors.any? %>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", ingredients_path, class:'btn btn-default' %>
  
<% end %>

app/views/ingredients/index.html.erb
<h2>Ingredients</h2>

<table class="table table-striped">
  <tr>
    <th>Ingredient Name</th>
    <th>Actions</th>
  </tr>

  <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <td><%= link_to 'Edit', edit_ingredient_path(ingredient.id) %> | <%= link_to 'Delete', ingredient_path(ingredient), method: :delete, data: {confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/ingredients/new.html.erb
<h2> Add New Ingredient</h2>

<%= form_for @ingredient do |f| %>
  <!-- Check for errors -->
  <% if @ingredient.errors.any? %>
    <% @ingredient.errors.full_messages.each do |msg| %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class:'form-control' %><br />
  </div>

  <%= f.submit "Submit", class:'btn btn-primary' %>
  <%= link_to "Cancel", ingredients_path, class:'btn btn-default' %>
  
<% end %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>Copyrigth &copy; 2018, All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class ="container" id='header-content'>
    <h1><i><b>Drink For Tonight </b></i><small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'Home', root_path %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to 'About', about_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="hide-option" title="You don't know what you can do with the ingredients that you have? Check it out!" <%= link_to 'Find Drink!', find_drink_path %></a>            
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Add new</a>
        <div class="dropdown-menu" aria-labelledby="dropdown03">
          <a class="dropdown-item" <%= link_to 'Drink', new_drink_path %></a>
          <a class="dropdown-item disabled" id="show-option" title="Demo version. If you are intrested in full version - hire me! :)">Primary Alcohol</a>
          <a class="dropdown-item disabled" id="show-option" title="Demo version. If you are intrested in full version - hire me! :)">Ingredient</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Users</a>
        <div class="dropdown-menu" aria-labelledby="dropdown03">
          <a class="dropdown-item" <%= link_to 'Sign Up', new_user_registration_path %></a>
          <a class="dropdown-item" <%= link_to 'Sign In', new_user_session_path %></a>
          <a class="dropdown-item" <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_rails_default.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title ? @page_title : 'Welcome' %> | Drink For Tonight </title>
    <%= render 'layouts/rails_default' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/header' %>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <!-- Alerts & Messages -->
          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar' %>
          </div>
        </div>  
      </div>
    </section>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
  <div class="well">
    <h3>Drink For Tonight</h3>
    <ul>
      <li>Dariusz Zagożdżon</li></br>
      <i class="fab fa-github"></i><a href="https://github.com/dzagozdzon" target="_blank"> Github</a></br></br>
      <i class="fab fa-linkedin"></i><a href="https://www.linkedin.com/in/dariusz-zagożdżon-b6a324154/" target="_blank"> Linkedin</a></br></br>
      <i class="fas fa-at"></i><a href="mailto:zagozdzond@gmail.com"> Email</br></br>
    </ul>
  </div>
<% end %>

<% if params[:controller] == 'drinks' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">
    <% @categories.each do |category| %>
      <%= link_to category.name, category_path(category.id), class:'list-group-item' %>
    <% end %>
</div>
<% end %>